
extends: eslint:recommended
root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
  - no-null
  - jest
  - cypress
env:
  node: true
  jest/globals: true
  cypress/globals: true
rules:

  no-null/no-null:
    - error

  # Possible errors
  comma-dangle:
    - error
  no-async-promise-executor:
    - error
  no-console:
    - error
  no-loss-of-precision:
    - error
  no-promise-executor-return:
    - error
  no-unsafe-optional-chaining:
    - error

  # Best practices
  array-callback-return:
    - error
  block-scoped-var:
    - error
  curly:
    - error
    - all
  default-case:
    - error
  default-case-last:
    - error
  default-param-last:
    - error
  dot-location:
    - error
    - property
  dot-notation:
    - error
  eqeqeq:
    - error
    - always
  no-alert:
    - error
  no-caller:
    - error
  no-case-declarations:
    - error
  no-else-return:
    - error
    - allowElseIf: true
  no-eq-null:
    - error
  no-eval:
    - error
  no-extend-native:
    - error
  no-extra-bind:
    - error
  no-floating-decimal:
    - error
  no-implicit-coercion:
    - error
  no-implicit-globals:
    - error
  no-implied-eval:
    - error
  no-invalid-this:
    - error
  no-iterator:
    - error
  no-lone-blocks:
    - error
  no-loop-func:
    - error
  no-magic-numbers:
    - error
  no-multi-spaces:
    - error
  no-multi-str:
    - error
  no-new:
    - error
  no-new-func:
    - error
  no-new-wrappers:
    - error
  no-nonoctal-decimal-escape:
    - error
  no-octal-escape:
    - error
  no-param-reassign:
    - error
  no-proto:
    - error
  no-redeclare:
    - error
  no-return-assign:
    - error
  no-return-await:
    - error
  no-script-url:
    - error
  no-self-assign:
    - error
  no-self-compare:
    - error
  no-sequences:
    - error
  no-throw-literal:
    - error
  no-unused-expressions:
    - error
  no-useless-call:
    - error
  no-useless-catch:
    - error
  no-useless-concat:
    - error
  no-useless-escape:
    - error
  no-void:
    - error
  no-with:
    - error
  prefer-named-capture-group:
    - error
  prefer-promise-reject-errors:
    - error
  prefer-regex-literals:
    - error
  radix:
    - error
  require-await:
    - error
  vars-on-top:
    - error
  yoda:
    - error

  # Variables
  no-delete-var:
    - error
  no-label-var:
    - error
  no-shadow-restricted-names:
    - error
  no-undef:
    - error
  no-unused-vars:
    - error
  no-use-before-define:
    - error

  # Stylistic issues
  array-bracket-spacing:
    - error
  block-spacing:
    - error
  brace-style:
    - error
  comma-spacing:
    - error
  comma-style:
    - error
  computed-property-spacing:
    - error
  consistent-this:
    - error
  eol-last:
    - error
  func-call-spacing:
    - error
  func-name-matching:
    - error
  func-style:
    - error
    - expression
  implicit-arrow-linebreak:
    - error
    - beside
  indent:
    - error
    - 2
  key-spacing:
    - error
  keyword-spacing:
    - error
  linebreak-style:
    - error
  lines-between-class-members:
    - error
  max-len:
    - error
    - ignoreUrls: true
    - ignorePattern: (import|eslint-disable)
  max-params:
    - error
    - max: 4
  max-statements-per-line:
    - error
  multiline-comment-style:
    - error
  new-parens:
    - error
  newline-per-chained-call:
    - error
  no-array-constructor:
    - error
  no-bitwise:
    - error
  no-continue:
    - error
  no-lonely-if:
    - error
  no-mixed-operators:
    - error
  no-mixed-spaces-and-tabs:
    - error
  no-multi-assign:
    - error
  no-multiple-empty-lines:
    - error
  no-negated-condition:
    - error
  no-nested-ternary:
    - error
  no-new-object:
    - error
  no-plusplus:
    - error
  no-trailing-spaces:
    - error
  no-unneeded-ternary:
    - error
  no-whitespace-before-property:
    - error
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
  one-var:
    - error
    - never
  one-var-declaration-per-line:
    - error
    - always
  operator-assignment:
    - error
    - never
  operator-linebreak:
    - error
    - before
  prefer-object-spread:
    - error
  quotes:
    - error
    - double
  semi:
    - error
  semi-spacing:
    - error
  semi-style:
    - error
    - last
  space-before-blocks:
    - error
  space-before-function-paren:
    - error
  space-in-parens:
    - error
  space-infix-ops:
    - error
  space-unary-ops:
    - error
  spaced-comment:
    - error
  switch-colon-spacing:
    - error
  template-tag-spacing:
    - error
  wrap-regex:
    - error

  # ECMAScript 6
  arrow-parens:
    - error
  arrow-spacing:
    - error
  constructor-super:
    - error
  no-class-assign:
    - error
  no-confusing-arrow:
    - error
  no-const-assign:
    - error
  no-dupe-class-members:
    - error
  no-new-symbol:
    - error
  no-this-before-super:
    - error
  no-useless-computed-key:
    - error
  no-useless-rename:
    - error
  no-var:
    - error
  object-shorthand:
    - error
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  prefer-destructuring:
    - error
  prefer-rest-params:
    - error
  prefer-spread:
    - error
  prefer-template:
    - error
  require-yield:
    - error
  rest-spread-spacing:
    - error
  template-curly-spacing:
    - error
  yield-star-spacing:
    - error

  # Typescript
  "@typescript-eslint/array-type":
    - error
  "@typescript-eslint/consistent-indexed-object-style":
    - error
  "@typescript-eslint/consistent-type-assertions":
    - error
    - assertionStyle: "as"
  "@typescript-eslint/consistent-type-definitions":
    - error
    - interface
  "@typescript-eslint/explicit-function-return-type":
    - error
  "@typescript-eslint/member-delimiter-style":
    - error
  "@typescript-eslint/method-signature-style":
    - error
    - property
  "@typescript-eslint/naming-convention":
    - error
  "@typescript-eslint/no-confusing-non-null-assertion":
    - error
  "@typescript-eslint/no-confusing-void-expression":
    - error
  "@typescript-eslint/no-dynamic-delete":
    - error
  "@typescript-eslint/no-empty-interface":
    - error
  "@typescript-eslint/no-explicit-any":
    - error
  "@typescript-eslint/no-extra-non-null-assertion":
    - error
  "@typescript-eslint/no-floating-promises":
    - error
  "@typescript-eslint/no-for-in-array":
    - error
  "@typescript-eslint/no-inferrable-types":
    - error
  "@typescript-eslint/no-invalid-void-type":
    - error
  "@typescript-eslint/no-misused-new":
    - error
  "@typescript-eslint/no-namespace":
    - error
  "@typescript-eslint/no-require-imports":
    - error
  "@typescript-eslint/no-this-alias":
    - error
  "@typescript-eslint/no-unnecessary-boolean-literal-compare":
    - error
  "@typescript-eslint/no-unnecessary-condition":
    - error
  "@typescript-eslint/no-unnecessary-qualifier":
    - error
  "@typescript-eslint/no-unnecessary-type-arguments":
    - error
  "@typescript-eslint/no-unnecessary-type-assertion":
    - error
  "@typescript-eslint/no-unnecessary-type-constraint":
    - error
  "@typescript-eslint/no-unsafe-argument":
    - error
  "@typescript-eslint/no-unsafe-return":
    - error
  "@typescript-eslint/non-nullable-type-assertion-style":
    - error
  "@typescript-eslint/prefer-as-const":
    - error
  "@typescript-eslint/prefer-enum-initializers":
    - error
  "@typescript-eslint/prefer-for-of":
    - error
  "@typescript-eslint/prefer-function-type":
    - error
  "@typescript-eslint/prefer-includes":
    - error
  "@typescript-eslint/prefer-literal-enum-member":
    - error
  "@typescript-eslint/prefer-namespace-keyword":
    - error
  "@typescript-eslint/prefer-nullish-coalescing":
    - error
  "@typescript-eslint/prefer-optional-chain":
    - error
  "@typescript-eslint/prefer-reduce-type-parameter":
    - error
  "@typescript-eslint/prefer-regexp-exec":
    - error
  "@typescript-eslint/prefer-string-starts-ends-with":
    - error
  "@typescript-eslint/promise-function-async":
    - error
  "@typescript-eslint/require-array-sort-compare":
    - error
  "@typescript-eslint/restrict-plus-operands":
    - error
  "@typescript-eslint/switch-exhaustiveness-check":
    - error
  "@typescript-eslint/triple-slash-reference":
    - error
  "@typescript-eslint/type-annotation-spacing":
    - error
  "@typescript-eslint/unified-signatures":
    - error
